# general settings
# name: debug
name: seed_0
model_type: SimCLRModel
manual_seed: 0
cudnn_deterministic: true

# common settings
common:
  num_frame: &num_frame 1800
  frame_skip: &frame_skip 12
  num_prev_frames: &num_prev_frames 3
  num_next_frames: &num_next_frames 3
  out_emb_size: &out_emb_size 128

# dataset and data loader settings
datasets:
  train:
    name: train_1830
    type: MouseVideoDataset
    video_dir: /cache/frames
    frame_number_map_path: ../dataset/mouse/frame_number_map.npy
    num_clip: 4
    num_frame: *num_frame
    frame_skip: *frame_skip
    num_prev_frames: *num_prev_frames
    num_next_frames: *num_next_frames
    frame_size: [224, 224]
    has_label: false

    # data loader
    batch_size_per_gpu: 64
    num_worker_per_gpu: 4
    pin_memory: true

  # val:
  #   name: val_784
  #   type: MouseVideoDataset
  #   video_dir: /cache/frames
  #   frame_number_map_path: ../dataset/mouse/frame_number_map_training.npy
  #   num_clip: 2
  #   num_frame: *num_frame
  #   frame_skip: *frame_skip
  #   num_prev_frames: *num_prev_frames
  #   num_next_frames: *num_next_frames
  #   frame_size: [256, 256]
  #   has_label: true
  #   keypoint_path: "/cache/user_train.npy"

  #   # data loader
  #   batch_size_per_gpu: 225
  #   num_worker_per_gpu: 4
  #   pin_memory: true

  test:
    name: test_1830
    type: MouseVideoDataset
    video_dir: /cache/frames
    frame_number_map_path: ../dataset/mouse/frame_number_map.npy
    num_clip: 2
    num_frame: *num_frame
    frame_skip: *frame_skip
    num_prev_frames: *num_prev_frames
    num_next_frames: *num_next_frames
    frame_size: [256, 256]
    has_label: false

    # data loader
    batch_size_per_gpu: 225
    num_worker_per_gpu: 4
    pin_memory: true

# network structures
network:
  type: SimCLR
  in_channels: 7
  out_emb_size: *out_emb_size

# path
path:
  pretrain_network: ~
  strict_load: true

# training settings
train:
  optim:
    type: Adam
    lr: !!float 1e-4
    weight_decay: !!float 1e-6
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 100000
  # iter_per_epoch: 3.3M / batch_size_per_gpu / world_size
  warmup_iter: -1 # -1: no warm up

# test settings
test:
  test_freq: 2000
  st_iter: 0
  ed_iter: 100000

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_wandb: false

find_unused_parameters: true
